export type WalletErrorCode =
  | 'WALLET_NOT_FOUND'
  | 'WALLET_SERVICE_UNAVAILABLE'
  | 'WALLET_SUSPENDED'
  | 'WALLET_CLOSED'
  | 'WALLET_AMOUNT_INVALID'
  | 'WALLET_INSUFFICIENT_BALANCE'
  | 'WALLET_IDEMPOTENCY_CONFLICT'
  | 'WALLET_TRANSACTION_NOT_FOUND'
  | 'WALLET_TRANSACTION_ALREADY_REVERSED'
  | 'WALLET_TRANSACTION_NOT_REVERSIBLE'
  | 'WALLET_LEDGER_INVARIANT_VIOLATION'
  | 'WALLET_RECONCILIATION_MISMATCH'
  | 'WALLET_PERMISSION_DENIED'
  | 'WALLET_PERSISTENCE_FAILURE';

export class WalletError extends Error {
  public constructor(public readonly code: WalletErrorCode) {
    super(code);
    this.name = 'WalletError';
  }
}
