export type MatchmakingErrorCode =
  | 'MATCHMAKING_REQUEST_NOT_FOUND'
  | 'MATCHMAKING_ACTIVE_REQUEST_EXISTS'
  | 'MATCHMAKING_ACCOUNT_INVALID'
  | 'MATCHMAKING_CATALOG_INVALID'
  | 'MATCHMAKING_RULESET_INVALID'
  | 'MATCHMAKING_REQUEST_EXPIRED'
  | 'MATCHMAKING_REQUEST_STATE_INVALID'
  | 'MATCHMAKING_PROPOSAL_NOT_FOUND'
  | 'MATCHMAKING_PROPOSAL_EXPIRED'
  | 'MATCHMAKING_PROPOSAL_STATE_INVALID'
  | 'MATCHMAKING_PROPOSAL_OWNERSHIP_INVALID'
  | 'MATCHMAKING_COMPATIBILITY_FAILURE'
  | 'MATCHMAKING_CONFLICT'
  | 'MATCHMAKING_UNAVAILABLE'
  | 'MATCHMAKING_PERSISTENCE_FAILURE'
  | 'MATCHMAKING_CRITERIA_INVALID';
export class MatchmakingError extends Error {
  public constructor(public readonly code: MatchmakingErrorCode) {
    super(code.toLowerCase().replaceAll('_', ' '));
    this.name = 'MatchmakingError';
  }
}
