export type NotificationErrorCode =
  | 'NOTIFICATION_NOT_FOUND'
  | 'NOTIFICATION_OWNERSHIP_INVALID'
  | 'NOTIFICATION_PAYLOAD_INVALID'
  | 'NOTIFICATION_TEMPLATE_NOT_FOUND'
  | 'NOTIFICATION_DEDUPLICATION_CONFLICT'
  | 'NOTIFICATION_PREFERENCE_INVALID'
  | 'NOTIFICATION_REQUIRED_CHANNEL'
  | 'NOTIFICATION_OUTBOX_NOT_FOUND'
  | 'NOTIFICATION_OUTBOX_STATE_INVALID'
  | 'NOTIFICATION_DELIVERY_UNAVAILABLE'
  | 'NOTIFICATION_DELIVERY_RETRY_EXHAUSTED'
  | 'NOTIFICATION_PERSISTENCE_FAILURE'
  | 'NOTIFICATION_SERVICE_UNAVAILABLE';

export class NotificationError extends Error {
  public constructor(public readonly code: NotificationErrorCode) {
    super(code);
    this.name = 'NotificationError';
  }
}
