import { ArgumentsHost, Catch, HttpStatus, type ExceptionFilter } from '@nestjs/common';
import {
  MatchDisputeError,
  MatchError,
  MatchEvidenceError,
  MatchResultError,
} from '@arena-core/matches';

const statuses: Record<string, number> = {
  MATCH_NOT_FOUND: HttpStatus.NOT_FOUND,
  MATCH_CREATION_CONFLICT: HttpStatus.CONFLICT,
  MATCH_PROPOSAL_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_SNAPSHOT_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_PARTICIPANT_NOT_FOUND: HttpStatus.NOT_FOUND,
  MATCH_READY_DEADLINE_EXPIRED: HttpStatus.GONE,
  MATCH_STATE_TRANSITION_INVALID: HttpStatus.CONFLICT,
  MATCH_PERMISSION_DENIED: HttpStatus.FORBIDDEN,
  MATCH_SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_PERSISTENCE_FAILURE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_START_INVALID: HttpStatus.CONFLICT,
  MATCH_ALREADY_STARTED: HttpStatus.CONFLICT,
  MATCH_RESULT_NOT_FOUND: HttpStatus.NOT_FOUND,
  MATCH_RESULT_SUBMISSION_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_RESULT_SUBMISSION_DEADLINE_EXPIRED: HttpStatus.GONE,
  MATCH_RESULT_ALREADY_FINALIZED: HttpStatus.CONFLICT,
  MATCH_RESULT_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_RESULT_WITHDRAW_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_RESULT_CONFLICT_NOT_FOUND: HttpStatus.NOT_FOUND,
  MATCH_RESULT_RESOLUTION_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_RESULT_PERMISSION_DENIED: HttpStatus.FORBIDDEN,
  MATCH_RESULT_SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_RESULT_PERSISTENCE_FAILURE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_EVIDENCE_NOT_FOUND: HttpStatus.NOT_FOUND,
  MATCH_EVIDENCE_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_EVIDENCE_SUBMISSION_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_EVIDENCE_WITHDRAW_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_EVIDENCE_SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_EVIDENCE_PERSISTENCE_FAILURE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_DISPUTE_NOT_FOUND: HttpStatus.NOT_FOUND,
  MATCH_DISPUTE_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_DISPUTE_OPEN_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_DISPUTE_ALREADY_ACTIVE: HttpStatus.CONFLICT,
  MATCH_DISPUTE_WINDOW_EXPIRED: HttpStatus.GONE,
  MATCH_DISPUTE_RESPONSE_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_DISPUTE_CANCEL_NOT_ALLOWED: HttpStatus.CONFLICT,
  MATCH_DISPUTE_STATE_INVALID: HttpStatus.CONFLICT,
  MATCH_DISPUTE_ASSIGNMENT_INVALID: HttpStatus.CONFLICT,
  MATCH_DISPUTE_RESOLUTION_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  MATCH_DISPUTE_PERMISSION_DENIED: HttpStatus.FORBIDDEN,
  MATCH_DISPUTE_SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,
  MATCH_DISPUTE_PERSISTENCE_FAILURE: HttpStatus.SERVICE_UNAVAILABLE,
};
@Catch(MatchError, MatchResultError, MatchEvidenceError, MatchDisputeError)
export class MatchesHttpFilter implements ExceptionFilter {
  public catch(
    error: MatchError | MatchResultError | MatchEvidenceError | MatchDisputeError,
    host: ArgumentsHost,
  ): void {
    host
      .switchToHttp()
      .getResponse<{ status(code: number): { json(body: unknown): void } }>()
      .status(statuses[error.code] ?? 500)
      .json({ error: { code: error.code, message: 'Match operation could not be completed.' } });
  }
}
