export type MatchFinanceErrorCode =
  | 'MATCH_ENTRY_NOT_REQUIRED'
  | 'MATCH_ENTRY_RESERVATION_NOT_FOUND'
  | 'MATCH_ENTRY_RESERVATION_ALREADY_EXISTS'
  | 'MATCH_ENTRY_RESERVATION_INSUFFICIENT_BALANCE'
  | 'MATCH_ENTRY_RESERVATION_EXPIRED'
  | 'MATCH_ENTRY_RESERVATION_STATE_INVALID'
  | 'MATCH_ENTRY_RESERVATION_MATCH_INVALID'
  | 'MATCH_ENTRY_RESERVATION_PARTICIPANT_INVALID'
  | 'MATCH_ENTRY_RESERVATION_IDEMPOTENCY_CONFLICT'
  | 'MATCH_ENTRY_RESERVATION_REFUND_NOT_ALLOWED'
  | 'MATCH_ENTRY_RESERVATION_RELEASE_NOT_ALLOWED'
  | 'MATCH_ESCROW_INVARIANT_VIOLATION'
  | 'MATCH_FINANCE_SERVICE_UNAVAILABLE'
  | 'MATCH_FINANCE_PERSISTENCE_FAILURE';

export class MatchFinanceError extends Error {
  public constructor(public readonly code: MatchFinanceErrorCode) {
    super(code);
    this.name = 'MatchFinanceError';
  }
}
