export type MatchSettlementErrorCode =
  | 'MATCH_SETTLEMENT_NOT_FOUND'
  | 'MATCH_SETTLEMENT_ALREADY_EXISTS'
  | 'MATCH_SETTLEMENT_NOT_ELIGIBLE'
  | 'MATCH_SETTLEMENT_DELAY_NOT_ELAPSED'
  | 'MATCH_SETTLEMENT_ACTIVE_DISPUTE'
  | 'MATCH_SETTLEMENT_RESULT_INVALID'
  | 'MATCH_SETTLEMENT_RESERVATION_INVALID'
  | 'MATCH_SETTLEMENT_ESCROW_MISMATCH'
  | 'MATCH_SETTLEMENT_IDEMPOTENCY_CONFLICT'
  | 'MATCH_SETTLEMENT_ALREADY_FINAL'
  | 'MATCH_SETTLEMENT_SERVICE_UNAVAILABLE'
  | 'MATCH_SETTLEMENT_PERSISTENCE_FAILURE';
export class MatchSettlementError extends Error {
  public constructor(public readonly code: MatchSettlementErrorCode) {
    super(code);
    this.name = 'MatchSettlementError';
  }
}
