ALTER TYPE "game_account_status" ADD VALUE IF NOT EXISTS 'DRAFT' BEFORE 'PENDING';
ALTER TYPE "game_account_status" ADD VALUE IF NOT EXISTS 'CHANGES_REQUESTED' AFTER 'REJECTED';

ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'CREATE' BEFORE 'VERIFY';
ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'UPDATE' AFTER 'CREATE';
ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'SUBMIT' AFTER 'UPDATE';
ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'REQUEST_CHANGES' AFTER 'REJECT';
ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'DELETE' AFTER 'DISCONNECT';
ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'RESTORE_BY_USER' AFTER 'DELETE';
ALTER TYPE "game_account_review_action" ADD VALUE IF NOT EXISTS 'PRIMARY_CHANGE' AFTER 'RESTORE_BY_USER';
