#!/usr/bin/env bash
set -Eeuo pipefail

source "$(dirname "$0")/lib/common.sh"
source "$SCRIPT_DIR/lib/validation.sh"
source "$SCRIPT_DIR/lib/database-boundary.sh"

usage() {
  cat >&2 <<'USAGE'
Usage:
  harden-external-postgres.sh INVENTORY
  harden-external-postgres.sh INVENTORY --apply

Without --apply the script performs a read-only audit.
USAGE
}

[[ $EUID -eq 0 ]] || die "run as root"

inventory="${1:-}"
mode="${2:-}"

[[ -n "$inventory" ]] || {
  usage
  exit 2
}

[[ "$mode" == "" || "$mode" == "--apply" ]] || {
  usage
  exit 2
}

load_inventory "$inventory"

[[ "$POSTGRES_MODE" == external ]] ||
  die "PostgreSQL host hardening requires POSTGRES_MODE=external"

command -v docker >/dev/null || die "docker is required"
command -v psql >/dev/null || die "psql is required"
command -v pg_isready >/dev/null || die "pg_isready is required"
command -v ss >/dev/null || die "ss is required"

network_name="${POSTGRES_DOCKER_NETWORK:-arena_db_egress}"

if ! docker network inspect "$network_name" >/dev/null 2>&1; then
  discovered="$(
    docker network ls       --filter label=com.docker.compose.project=arena       --filter label=com.docker.compose.network=db_egress       --format '{{.Name}}' |
    head -1
  )"

  [[ -n "$discovered" ]] ||
    die "Arena database egress network was not found"

  network_name="$discovered"
fi

read -r gateway subnet internal < <(
  docker network inspect "$network_name"     --format '{{(index .IPAM.Config 0).Gateway}} {{(index .IPAM.Config 0).Subnet}} {{.Internal}}'
)

[[ "$internal" == false ]] ||
  die "database egress network must not be internal"

is_private_ipv4 "$gateway" ||
  die "database egress gateway is not private"

[[ "$subnet" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]] ||
  die "database egress subnet is not valid IPv4 CIDR"

config_file="$(
  sudo -u postgres psql -At -d postgres -c 'SHOW config_file'
)"

hba_file="$(
  sudo -u postgres psql -At -d postgres -c 'SHOW hba_file'
)"

port="$(
  sudo -u postgres psql -At -d postgres -c 'SHOW port'
)"

[[ "$port" == 5432 ]] ||
  die "expected PostgreSQL port 5432"

for path in "$config_file" "$hba_file"; do
  [[ -f "$path" && ! -L "$path" ]] ||
    die "PostgreSQL configuration must be a regular non-symlink file: $path"

  [[ -r "$path" && -w "$path" ]] ||
    die "PostgreSQL configuration must be readable and writable by root: $path"
done

current_listeners="$(
  sudo -u postgres psql -At -d postgres -c 'SHOW listen_addresses'
)"

printf 'network=%s\n' "$network_name"
printf 'gateway=%s\n' "$gateway"
printf 'subnet=%s\n' "$subnet"
printf 'config_file=%s\n' "$config_file"
printf 'hba_file=%s\n' "$hba_file"
printf 'current_listen_addresses=%s\n' "$current_listeners"
printf 'target_listen_addresses=127.0.0.1,%s\n' "$gateway"

if [[ "$mode" != "--apply" ]]; then
  echo "Audit completed. No files or services were changed."
  exit 0
fi

backup_root="/var/lib/arena/postgres-hardening"
backup_dir="$backup_root/$(date -u +'%Y%m%dT%H%M%SZ')"

install -d -o root -g root -m 0700 "$backup_root"
install -d -o root -g root -m 0700 "$backup_dir"

auto_conf="$(
  sudo -u postgres psql -At -d postgres -c "
    SELECT setting || '/postgresql.auto.conf'
    FROM pg_settings
    WHERE name = 'data_directory'
  "
)"

cp -a "$config_file" "$backup_dir/postgresql.conf"
cp -a "$hba_file" "$backup_dir/pg_hba.conf"

hba_owner="$(stat -c %u "$hba_file")"
hba_group="$(stat -c %g "$hba_file")"
hba_mode="$(stat -c %a "$hba_file")"

if [[ -f "$auto_conf" ]]; then
  cp -a "$auto_conf" "$backup_dir/postgresql.auto.conf"
else
  : >"$backup_dir/postgresql.auto.conf.absent"
fi

restore_previous_configuration() {
  warn "restoring previous PostgreSQL configuration"

  cp -a "$backup_dir/postgresql.conf" "$config_file"
  cp -a "$backup_dir/pg_hba.conf" "$hba_file"

  if [[ -f "$backup_dir/postgresql.auto.conf" ]]; then
    cp -a "$backup_dir/postgresql.auto.conf" "$auto_conf"
  else
    rm -f "$auto_conf"
  fi

  systemctl restart postgresql || true
}

trap restore_previous_configuration ERR INT TERM

managed_hba="$(
  cat <<HBA
# BEGIN ARENA MANAGED DATABASE BOUNDARY
# Generated by harden-external-postgres.sh
host    $POSTGRES_DB    $POSTGRES_USER    127.0.0.1/32    scram-sha-256
host    $POSTGRES_DB    $POSTGRES_USER    ::1/128         scram-sha-256
host    $POSTGRES_DB    $POSTGRES_USER    $subnet         scram-sha-256
host    all             all               0.0.0.0/0       reject
host    all             all               ::/0            reject
# END ARENA MANAGED DATABASE BOUNDARY
HBA
)"

python3 - "$hba_file" "$managed_hba" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
managed = sys.argv[2]

begin = "# BEGIN ARENA MANAGED DATABASE BOUNDARY"
end = "# END ARENA MANAGED DATABASE BOUNDARY"

source = path.read_text(encoding="utf-8")
lines = source.splitlines()

output = []
inside = False

for line in lines:
    if line.strip() == begin:
        inside = True
        continue

    if inside and line.strip() == end:
        inside = False
        continue

    if not inside:
        output.append(line)

if inside:
    raise SystemExit("unterminated existing Arena HBA block")

path.write_text(
    managed.rstrip() + "\n\n" + "\n".join(output).lstrip() + "\n",
    encoding="utf-8",
)
PY

chown "$hba_owner:$hba_group" "$hba_file"
chmod "$hba_mode" "$hba_file"

sudo -u postgres psql -v ON_ERROR_STOP=1 -d postgres -c   "ALTER SYSTEM SET listen_addresses TO '127.0.0.1,$gateway';"

hba_errors="$(
  sudo -u postgres psql -At -d postgres -c "
    SELECT count(*)
    FROM pg_hba_file_rules
    WHERE error IS NOT NULL
  "
)"

[[ "$hba_errors" == 0 ]] ||
  die "generated pg_hba.conf is invalid"

systemctl restart postgresql
systemctl is-active --quiet postgresql

pg_isready   -h 127.0.0.1   -p 5432   -d "$POSTGRES_DB"   -U "$POSTGRES_USER"   -t 10

docker run   --rm   --network "$network_name"   --add-host host.docker.internal:host-gateway   -v "$SERVER_APP_ROOT/shared/secrets:/run/arena-secrets:ro"   postgres:17.10-alpine3.23   sh -ec   'psql --dbname="$(cat /run/arena-secrets/DATABASE_DIRECT_URL)" -v ON_ERROR_STOP=1 -Atc "SELECT 1"'

verify_external_postgres_boundary

trap - ERR INT TERM

echo "PostgreSQL host boundary hardened successfully."
echo "Backup: $backup_dir"
