import type { AdminPermission } from './types';

export const ADMIN_PREVIEW_PERMISSIONS: readonly AdminPermission[] = [
  'users.read',
  'users.manage_status',
  'users.manage_sessions',
  'users.verify_email',
  'roles.read',
  'roles.assign',
  'roles.manage',
  'audit.read',
  'support.read',
  'support.manage',
  'timeline.read',
  'diagnostics.read',
  'notifications.read',
  'notifications.retry',
  'notifications.manage',
  'games.read',
  'games.manage',
  'platforms.manage',
  'rulesets.manage',
  'game_accounts.read',
  'game_accounts.verify',
  'game_accounts.suspend',
  'matches.read',
  'matches.manage',
  'match_results.read',
  'match_results.resolve',
  'match_disputes.read',
  'match_disputes.assign',
  'match_disputes.review',
  'matchmaking.read',
  'wallets.read',
  'wallets.issue',
  'wallets.adjust',
  'wallets.reverse',
  'wallets.reconcile',
  'match_finance.read',
  'match_finance.manage',
  'match_finance.reconcile',
  'match_settlements.read',
  'match_settlements.manage',
  'match_settlements.reconcile',
  'ratings.read',
  'ratings.manage',
  'ratings.reconcile',
];

export const isAdminUiPreviewEnabled = () =>
  process.env.NODE_ENV !== 'production' && process.env.ADMIN_UI_PREVIEW === 'true';
