export type RatingErrorCode =
  | 'RATING_NOT_FOUND'
  | 'RATING_APPLICATION_NOT_ELIGIBLE'
  | 'RATING_APPLICATION_DELAY_NOT_ELAPSED'
  | 'RATING_APPLICATION_ACTIVE_DISPUTE'
  | 'RATING_APPLICATION_ALREADY_EXISTS'
  | 'RATING_APPLICATION_IDEMPOTENCY_CONFLICT'
  | 'RATING_APPLICATION_RESULT_INVALID'
  | 'RATING_APPLICATION_PARTICIPANT_INVALID'
  | 'RATING_POLICY_INVALID'
  | 'RATING_INVARIANT_VIOLATION'
  | 'LEADERBOARD_UNAVAILABLE'
  | 'RATING_SERVICE_UNAVAILABLE'
  | 'RATING_PERSISTENCE_FAILURE';

export class RatingError extends Error {
  public constructor(public readonly code: RatingErrorCode) {
    super(code);
    this.name = 'RatingError';
  }
}
