export const ADMIN_PERMISSION_CATALOG = [
  ['audit.read', 'Read administrative audit events.'],
  ['support.read', 'Read bounded support information.'],
  ['support.manage', 'Perform audited support operations.'],
  ['timeline.read', 'Read administrative entity timelines.'],
  ['diagnostics.read', 'Read sanitized operational diagnostics.'],
  ['notifications.read', 'Read notification administration data.'],
  ['notifications.retry', 'Retry eligible notification delivery.'],
  ['notifications.manage', 'Manage notification delivery state.'],
  ['games.read', 'Read game catalog administration data.'],
  ['games.manage', 'Manage game catalog entries.'],
  ['platforms.manage', 'Manage game platform configuration.'],
  ['rulesets.manage', 'Manage versioned competitive rulesets.'],
  ['game_accounts.read', 'Read player game accounts.'],
  ['game_accounts.verify', 'Verify player game accounts.'],
  ['game_accounts.suspend', 'Suspend or restore player game accounts.'],
  ['matches.read', 'Read match administration data.'],
  ['matches.manage', 'Manage eligible match lifecycle operations.'],
  ['match_results.read', 'Read match result administration data.'],
  ['match_results.resolve', 'Resolve disputed match results.'],
  ['match_disputes.read', 'Read match disputes.'],
  ['match_disputes.assign', 'Assign match dispute reviewers.'],
  ['match_disputes.review', 'Review and resolve match disputes.'],
  ['matchmaking.read', 'Read matchmaking administration data.'],
  ['wallets.read', 'Read wallet administration data.'],
  ['wallets.issue', 'Issue non-monetary wallet points.'],
  ['wallets.adjust', 'Apply audited wallet adjustments.'],
  ['wallets.reverse', 'Reverse eligible wallet transactions.'],
  ['wallets.reconcile', 'Reconcile wallet ledger state.'],
  ['match_finance.read', 'Read match finance state.'],
  ['match_finance.manage', 'Manage eligible match finance operations.'],
  ['match_finance.reconcile', 'Reconcile match finance state.'],
  ['match_settlements.read', 'Read match settlement state.'],
  ['match_settlements.manage', 'Manage eligible match settlements.'],
  ['match_settlements.reconcile', 'Reconcile match settlements.'],
  ['ratings.read', 'Read rating administration data.'],
  ['ratings.manage', 'Manage eligible rating operations.'],
  ['ratings.reconcile', 'Reconcile rating state.'],
] as const;
export type AdminPermissionKey = (typeof ADMIN_PERMISSION_CATALOG)[number][0];
export const ADMIN_PERMISSION_KEYS: readonly AdminPermissionKey[] = Object.freeze(
  ADMIN_PERMISSION_CATALOG.map(([key]) => key),
);
